INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 1');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 2');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 3');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 4');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 5');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 6');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 7');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 8');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 9');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 10');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 11');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 12');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 13');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 14');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 15');
INSERT INTO menu_category(menu_category_name) VALUES ('Menu Category 16');

INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 1');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 2');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 3');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 4');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 5');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 6');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 7');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 8');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 9');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 10');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 11');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 12');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 13');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 14');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 15');
INSERT INTO supply_category(supply_category_name) VALUES ('Supply Category 16');

INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 1', 'UOM 1');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 2', 'UOM 2');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 3', 'UOM 3');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 4', 'UOM 4');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 5', 'UOM 5');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 6', 'UOM 6');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 7', 'UOM 7');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 8', 'UOM 8');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 9', 'UOM 9');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 10', 'UOM 10');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 11', 'UOM 11');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 12', 'UOM 12');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 13', 'UOM 13');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 14', 'UOM 14');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 15', 'UOM 15');
INSERT INTO unit_of_measurement(unit_of_measurement_name, unit_of_measurement_abbreviation) VALUES ('Unit of Measurement 16', 'UOM 16');

