/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.exe.EscobarIMS.MainMenu;

import com.exe.EscobarIMS.MenuCategory.AddMenuCategory.Forms.AddMenuCategoryForm;
import com.exe.EscobarIMS.MenuCategory.ViewEditDeleteMenuCategory.Forms.ViewEditDeleteMenuCategoryForm;
import com.exe.EscobarIMS.Supplier.AddSupplier.Forms.AddSupplierForm;
import com.exe.EscobarIMS.Supplier.ViewEditDeleteSupplier.Forms.ViewEditDeleteSupplierForm;
import com.exe.EscobarIMS.Supply.AddSupply.Forms.AddSupplyForm;
import com.exe.EscobarIMS.Supply.ViewEditDeleteSupply.Forms.ViewEditDeleteSupplyForm;
import com.exe.EscobarIMS.SupplyCategory.AddSupplyCategory.Forms.AddSupplyCategoryForm;
import com.exe.EscobarIMS.SupplyCategory.ViewEditDeleteSupplyCategory.Forms.ViewEditDeleteSupplyCategoryForm;
import com.exe.EscobarIMS.UnitOfMeasurement.AddUnitOfMeasurement.Forms.AddUnitOfMeasurementForm;
import com.exe.EscobarIMS.UnitOfMeasurement.ViewEditDeleteUnitOfMeasurement.Forms.ViewEditDeleteUnitOfMeasurementForm;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.awt.event.ActionEvent;

/**
 *
 * @author Viver
 */

@Component
public class MainMenuForm extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuForm
     */
    
    @Autowired
    AddMenuCategoryForm addMenuCategoryForm;

    @Autowired
    ViewEditDeleteMenuCategoryForm viewEditDeleteMenuCategoryForm;

    @Autowired
    AddSupplyCategoryForm addSupplyCategoryForm;
    
    @Autowired
    ViewEditDeleteSupplyCategoryForm viewEditDeleteSupplyCategoryForm;

    @Autowired
    AddUnitOfMeasurementForm addUnitOfMeasurementForm;

    @Autowired
    ViewEditDeleteUnitOfMeasurementForm viewEditDeleteUnitOfMeasurementForm;
    
    @Autowired
    AddSupplierForm addSupplierForm;

    @Autowired
    ViewEditDeleteSupplierForm viewEditDeleteSupplierForm;
    
    @Autowired
    AddSupplyForm addSupplyForm;
    
    @Autowired
    ViewEditDeleteSupplyForm viewEditDeleteSupplyForm;


    

    public MainMenuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigationPanel = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        transactionsLabel = new javax.swing.JLabel();
        supplyLabel = new javax.swing.JLabel();
        menuLabel = new javax.swing.JLabel();
        supplierLabel = new javax.swing.JLabel();
        unitOfMeasurementLabel = new javax.swing.JLabel();
        supplyCategoryLabel = new javax.swing.JLabel();
        menuCategoryLabel = new javax.swing.JLabel();
        addSupplyNavigationButton = new javax.swing.JButton();
        viewEditDeleteSupplyNavigationButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        addSupplierNavigationButton = new javax.swing.JButton();
        viewEditDeleteSupplierNavigationButton = new javax.swing.JButton();
        addUnitOfMeasurementNavigationButton = new javax.swing.JButton();
        viewEditDeleteUnitOfMeasurementNavigationButton = new javax.swing.JButton();
        viewEditDeleteMenuCategoryNavigationButton = new javax.swing.JButton();
        addMenuCategoryNavigationButton = new javax.swing.JButton();
        addSupplyCategoryNavigationButton = new javax.swing.JButton();
        viewEditDeleteSupplyCategoryNavigationButton = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navigationPanel.setBackground(new java.awt.Color(102, 102, 102));

        jButton4.setText("Add Transaction");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.setMinimumSize(new java.awt.Dimension(93, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        transactionsLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        transactionsLabel.setForeground(new java.awt.Color(255, 255, 255));
        transactionsLabel.setText("Transactions");
        transactionsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        supplyLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        supplyLabel.setForeground(new java.awt.Color(255, 255, 255));
        supplyLabel.setText("Supply");
        supplyLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        menuLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        menuLabel.setForeground(new java.awt.Color(255, 255, 255));
        menuLabel.setText("Menu");
        menuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        supplierLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        supplierLabel.setForeground(new java.awt.Color(255, 255, 255));
        supplierLabel.setText("Supplier");
        supplierLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        unitOfMeasurementLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        unitOfMeasurementLabel.setForeground(new java.awt.Color(255, 255, 255));
        unitOfMeasurementLabel.setText("Unit of Measurement");
        unitOfMeasurementLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        supplyCategoryLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        supplyCategoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        supplyCategoryLabel.setText("Supply Category");
        supplyCategoryLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        menuCategoryLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        menuCategoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        menuCategoryLabel.setText("Menu Category");
        menuCategoryLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        addSupplyNavigationButton.setText("Add Supply");
        addSupplyNavigationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addSupplyNavigationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplyNavigationButtonActionPerformed(evt);
            }
        });

        viewEditDeleteSupplyNavigationButton.setText("View/Edit/Delete Supplies");
        viewEditDeleteSupplyNavigationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewEditDeleteSupplyNavigationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEditDeleteSupplyNavigationButtonActionPerformed(evt);
            }
        });

        jButton7.setText("Add Menu");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("View//Edit/Delete Menus");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        addSupplierNavigationButton.setText("Add Supplier");
        addSupplierNavigationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addSupplierNavigationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplierNavigationButtonActionPerformed(evt);
            }
        });

        viewEditDeleteSupplierNavigationButton.setText("View/Delete/Edit Suppliers");
        viewEditDeleteSupplierNavigationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewEditDeleteSupplierNavigationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEditDeleteSupplierNavigationButtonActionPerformed(evt);
            }
        });

        addUnitOfMeasurementNavigationButton.setText("Add Unit of Measurement");
        addUnitOfMeasurementNavigationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addUnitOfMeasurementNavigationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUnitOfMeasurementNavigationButtonActionPerformed(evt);
            }
        });

        viewEditDeleteUnitOfMeasurementNavigationButton.setText("View/Edit/Delete Unit of Measurement");
        viewEditDeleteUnitOfMeasurementNavigationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewEditDeleteUnitOfMeasurementNavigationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEditDeleteUnitOfMeasurementNavigationButtonActionPerformed(evt);
            }
        });

        viewEditDeleteMenuCategoryNavigationButton.setText("View/Edit/Delete Menu Categories");
        viewEditDeleteMenuCategoryNavigationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewEditDeleteMenuCategoryNavigationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEditDeleteMenuCategoryNavigationButtonActionPerformed(evt);
            }
        });

        addMenuCategoryNavigationButton.setText("Add Menu Category");
        addMenuCategoryNavigationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addMenuCategoryNavigationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMenuCategoryNavigationButtonActionPerformed(evt);
            }
        });

        addSupplyCategoryNavigationButton.setText("Add Supply Category");
        addSupplyCategoryNavigationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addSupplyCategoryNavigationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplyCategoryNavigationButtonActionPerformed(evt);
            }
        });

        viewEditDeleteSupplyCategoryNavigationButton.setText("View/Edit/Delete Supply Categories");
        viewEditDeleteSupplyCategoryNavigationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewEditDeleteSupplyCategoryNavigationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEditDeleteSupplyCategoryNavigationButtonActionPerformed(evt);
            }
        });

        jButton13.setText("View Transactions");
        jButton13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Montserrat SemiBold", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Main Menu");

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navigationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(viewEditDeleteSupplyCategoryNavigationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addSupplyCategoryNavigationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(supplyCategoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewEditDeleteSupplierNavigationButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(supplierLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addSupplierNavigationButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(transactionsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewEditDeleteSupplyNavigationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(unitOfMeasurementLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addUnitOfMeasurementNavigationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewEditDeleteUnitOfMeasurementNavigationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(supplyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addSupplyNavigationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(menuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menuCategoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addMenuCategoryNavigationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewEditDeleteMenuCategoryNavigationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)))
                    .addGroup(navigationPanelLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel8)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transactionsLabel)
                    .addComponent(supplyLabel)
                    .addComponent(menuLabel))
                .addGap(18, 18, 18)
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSupplyNavigationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewEditDeleteSupplyNavigationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierLabel)
                    .addComponent(unitOfMeasurementLabel)
                    .addComponent(menuCategoryLabel))
                .addGap(18, 18, 18)
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSupplierNavigationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUnitOfMeasurementNavigationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addMenuCategoryNavigationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewEditDeleteSupplierNavigationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewEditDeleteUnitOfMeasurementNavigationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewEditDeleteMenuCategoryNavigationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(supplyCategoryLabel)
                .addGap(18, 18, 18)
                .addComponent(addSupplyCategoryNavigationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewEditDeleteSupplyCategoryNavigationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void addSupplyNavigationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplyNavigationButtonActionPerformed
        addSupplyForm.setVisible(true);
    }//GEN-LAST:event_addSupplyNavigationButtonActionPerformed

    private void viewEditDeleteSupplyNavigationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEditDeleteSupplyNavigationButtonActionPerformed
        viewEditDeleteSupplyForm.setVisible(true);
    }//GEN-LAST:event_viewEditDeleteSupplyNavigationButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void addSupplierNavigationButtonActionPerformed(ActionEvent evt) {
        addSupplierForm.setVisible(true);
    }

    private void viewEditDeleteSupplierNavigationButtonActionPerformed(ActionEvent evt) {
        viewEditDeleteSupplierForm.setVisible(true);
    }

    private void addUnitOfMeasurementNavigationButtonActionPerformed(ActionEvent evt) {
        addUnitOfMeasurementForm.setVisible(true);
    }

    private void viewEditDeleteUnitOfMeasurementNavigationButtonActionPerformed(ActionEvent evt) {
        viewEditDeleteUnitOfMeasurementForm.setVisible(true);
    }

    private void viewEditDeleteMenuCategoryNavigationButtonActionPerformed(ActionEvent evt) {
        viewEditDeleteMenuCategoryForm.setVisible(true);
    }

    private void addMenuCategoryNavigationButtonActionPerformed(ActionEvent evt) {
        addMenuCategoryForm.setVisible(true);
    }

    private void addSupplyCategoryNavigationButtonActionPerformed(ActionEvent evt) {
        addSupplyCategoryForm.setVisible(true);
    }

    private void viewEditDeleteSupplyCategoryNavigationButtonActionPerformed(ActionEvent evt) {
        viewEditDeleteSupplyCategoryForm.setVisible(true);
    }

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMenuCategoryNavigationButton;
    private javax.swing.JButton addSupplierNavigationButton;
    private javax.swing.JButton addSupplyCategoryNavigationButton;
    private javax.swing.JButton addSupplyNavigationButton;
    private javax.swing.JButton addUnitOfMeasurementNavigationButton;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel menuCategoryLabel;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JLabel supplierLabel;
    private javax.swing.JLabel supplyCategoryLabel;
    private javax.swing.JLabel supplyLabel;
    private javax.swing.JLabel transactionsLabel;
    private javax.swing.JLabel unitOfMeasurementLabel;
    private javax.swing.JButton viewEditDeleteMenuCategoryNavigationButton;
    private javax.swing.JButton viewEditDeleteSupplierNavigationButton;
    private javax.swing.JButton viewEditDeleteSupplyCategoryNavigationButton;
    private javax.swing.JButton viewEditDeleteSupplyNavigationButton;
    private javax.swing.JButton viewEditDeleteUnitOfMeasurementNavigationButton;
    // End of variables declaration//GEN-END:variables
}
